# Generated by Django 2.2 on 2020-05-28 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('recurring_task', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(default=None, to='organizer.ActivityCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_completed', models.PositiveSmallIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('activities', models.ManyToManyField(to='organizer.Activity')),
            ],
        ),
    ]
